### ISSUE TITLE
Setting ContentAlign to Left prints error.

### ISSUE THREAD

**Issue by eyeszack** [Delta456/box-cli-maker#10]
https://github.com/Delta456/box-cli-maker/blob/9758b768604d385557ae102160961fcb1dbfd8f4/util.go#L24

Hello,

Nice work on this project! I just wanted to point out that when you specify a ContentAlign of Left an error will be printed. It appears to be a missing else if check for Left. Ironically the else defaults to left align. :)

**Comment by Delta456** [comment]
Oh good find! Thanks! Can you do a PR as I am busy with other projects? Regards!

**Comment by Delta456** [comment]
Done https://github.com/Delta456/box-cli-maker/commit/18b6b8296c63fb18423e14b772c7eb70e9fbde6a
