### ISSUE TITLE
[BUG] long text fails to wrap

### ISSUE THREAD

**Issue by gennaro-tedesco** [Delta456/box-cli-maker#25]
**Describe the bug**
Text lines that are longer than terminal width fail to wrap inside the box

**To Reproduce**
You can reproduce the behaviour by simply creating a string that is longer than terminal width: notice that you can retrieve the current terminal length with
```
import (
    "golang.org/x/term"
)

width, _, err := term.GetSize(0)
if err != nil {
    return
}
```
and replicate a string of given `width`.

Then simply
```
Box.Print("title", long_string)
```
produces effects like [this](https://user-images.githubusercontent.com/15387611/152479859-d11cffdf-bc24-4100-9764-4dac0b4623e5.png).

**Expected behavior**
The box wraps text automatically. Ideally the user can specify wrap after a certain length.

**Workaround**
At the moment I am making use of [go-wordwrap](https://github.com/mitchellh/go-wordwrap) to wrap the text myself _before_ feeding it into the box.
```
import (
	"github.com/mitchellh/go-wordwrap"
)
Box.Print("title", wordwrap.WrapString(sb.String(), uint((2*width)/3)))
```

**Versions (please complete the following information, if relevant):**
```
Machine:   MacBookPro15,2
Kernel:     Darwin 21.2.0
OS         macOS 12.1.0 Monterey
Terminal   iTerm2 (Version 3.4.14)
Shell      /bin/zsh
```

**Comment by Delta456** [comment]
Thanks for raising the issue. I will see what I can do.

**Comment by Delta456** [comment]
Hmm I am thinking of making a flag like `AllowWrapping` when set to `true` will allow wrapping of lines else the lines won't be wrapped. I also would like to know if I should also let the user provide the number or `uint((2*width)/3))` should be used instead?

**Comment by gennaro-tedesco** [comment]
> I am thinking of making a flag like AllowWrapping when set to true will allow wrapping of lines 

Yes, this sounds like the best solution.

> if I should also let the user provide the number or `uint((2*width)/3))` should be used instead?

another idea could be, instead of `AllowWrapping = true/false`, to have a numerical parameter, say `WrappingWidth = 0,...,1` between 0 and 1 that directly specifies the size to wrap at, with 1 meaning "no wrap" or so. Which begs the question: is there any use case where users do _not_ want to wrap text? I cannot imagine any scenario where users may want to leave the text pending off terminal width 🤔 

In any case this probably depends on the implementation complexity and I would be happy already to have a boolean parameter that allows wrapping at a fixed length by default, just to avoid the boxes to be messed up in some cases.

**Comment by gennaro-tedesco** [comment]
By the way, just for reference, [this is the project](https://github.com/gennaro-tedesco/happyfish) I am working on and [here](https://github.com/gennaro-tedesco/happyfish/blob/d746c458bb858e1bef529b4a3e005da9a201f5ee/cmd/ui.go#L14-L38) is where I am invoking your library.

**Comment by Delta456** [comment]
In some scenarios people may want to pad according to their own needs so I think I will let the user allow it. By default it would be `uint((width*2)/3)`. 

What you think about this? 🤔

**Comment by Delta456** [comment]
After several testing, I will be using [`muesli/reflow`](https://github.com/muesli/reflow) instead of [`go-wordwrap`](https://github.com/mitchellh/go-wordwrap) because the former also has support for CJK, tabs and emojis and it provides several options.

**Comment by gennaro-tedesco** [comment]
Great idea, I am looking forward to the new release! :)

**Comment by Delta456** [comment]
> In some scenarios people may want to pad according to their own needs so I think I will let the user allow it. By default it would be `uint((width*2)/3)`.
> 
> What you think about this? 🤔
> 
> Also it looks like you are using a very old version of the library. `v2.2.2` is the latest version.

Please what you think about this

**Comment by gennaro-tedesco** [comment]
> In some scenarios people may want to pad according to their own needs so I think I will let the user allow it.

yes, I agree that giving the user more flexibility may help in many cases. Moreover 2/3 is also a good default!

> Also it looks like you are using a very old version of the library. v2.2.2 is the latest version

oooops, I just noticed it too. I will update the modules! What are the main differences (or do you have a page with new release notes I can read)?

**Comment by Delta456** [comment]
> oooops, I just noticed it too. I will update the modules! What are the main differences (or do you have a page with new release notes I can read)?

Yes, it is [here](https://github.com/Delta456/box-cli-maker/releases).

**Comment by Delta456** [comment]
Heads up. I have implemented this feature in this commit https://github.com/Delta456/box-cli-maker/pull/22/commits/d7a6d036685c0736876fb03222984296dc87dde7 you can read how the future API would be.

**Comment by gennaro-tedesco** [comment]
I am having a look, thank you!
