### ISSUE TITLE
[feature request] IO-independent output

### ISSUE THREAD

**Issue by nedpals** [Delta456/box-cli-maker#27]
**Is your feature request related to a problem? Please describe.**
Currently it only supports outputting to `os.Stdout`.

**Describe the solution you'd like**
Should take advantage of Go's `io.Writer` and have `Stdout`-specific configurations as a `io.Writer`-compliant type/struct. That way we can do stuff like simultaneous logging and displaying of output with `io.MultiWriter`

**Describe alternatives you've considered**

**Additional context**
See the [io](https://pkg.go.dev/io) package.

**Comment by Delta456** [comment]
After thinking about this throughout. This isn't needed but thanks for giving this suggestion!
