### ISSUE TITLE
[BUG] Formatting of the Top Title is lost 

### ISSUE THREAD

**Issue by tkanos** [Delta456/box-cli-maker#31]
**Describe the bug**
On the dev branch, If I write a Title and a text with formatting like `033[1m something \033[0m`
The text formatting stay as it should be. 
But the Title one loose its formatting.

**To Reproduce**
```
func main() {
        Box := box.New(box.Config{Px: 2, Py: 1, Type: "Single", Color: "Cyan", TitlePos: "Top"})
	Box.Print("\033[1mBroken\033[0m, sorry", "Btw \033[1mNot Broken\033[0m, very nice")
}
```
![Screenshot from 2022-10-04 01-11-55](https://user-images.githubusercontent.com/5888407/193739561-a77b089f-0c8a-4adb-8f78-2bdb7964530f.png)

As you see Broken is not anymore **Bold** as it should be.

The output string is :
```
"\x1b[36m┌ Broken, sorry ──────────────┐\x1b[0m\n\x1b[36m│\x1b[0m"
```
When it should be :
```
"\x1b[36m┌ \x1b[1mBroken\x1b[0m\x1b[36m, sorry ──────────────┐\x1b[0m"
```

You have to somehow split by the reset tag \x1b[0m and add the color \x1b[36m after again.

**Comment by Delta456** [comment]
Now I will take a look at this. Thanks

**Comment by Delta456** [comment]
I am not able to figure out how I am gonna support Bold and Color ANSI Codes together because whenever I try to make an exception either the former or latter don't work correctly. Can you help how should I handle this?

**Comment by tkanos** [comment]
I have an idea. I will try later.

**Comment by tkanos** [comment]
I have found a way BUT, is it what you want to do, because it will allow developers to also change the color of the title (I mean they will be more free to change the color of the title by them self).

Once I have time I do a PR to show to you.

**Comment by Delta456** [comment]
Fixed in https://github.com/Delta456/box-cli-maker/pull/22/commits/03e0487c5551b683d19d6cba3d02ddec804205ab
