### ISSUE TITLE
ASoC: Use `switch` case for checking the type of `Color`

### ISSUE THREAD

**Issue by Delta456** [Delta456/box-cli-maker#35]
There are a lot of if conditions for checking the type of `Color` which makes it very hard to read and debug. A switch case will improve readability and help to debug much better. 

For example [box.go#L192](https://github.com/Delta456/box-cli-maker/blob/master/box.go#L192-L239) is long, and with a switch case, it can be done much more efficiently.

**Comment by AniketNS** [comment]
Hey @Delta456, I can solve this issue. Please assign this issue to me.

**Comment by Delta456** [comment]
> Hey @Delta456, I can solve this issue. Please assign this issue to me.

Go ahead

**Comment by DaveSaah** [comment]
What's the progress of resolving this issue? Wanted to join in.

**Comment by Delta456** [comment]
Feel free to solve this issue.

**Comment by DaveSaah** [comment]
Alright

**Comment by Delta456** [comment]
Fixed in https://github.com/Delta456/box-cli-maker/commit/1ac023b47126a36e6a134236ff268b7a553e1174
